watchlist = [
    "Marvel's Luke Cage",
    "Halt and Catch Fire",
    "Scorpion",
    "DC's Legends of Tomorrow",
    "Supernatural",
    "The Big Bang Theory",
    "Arrow",
    "Blindspot",
    "Marvel's Agents of S.H.I.E.L.D.",
    "Last Man Standing",
    'American Horror Story',
    'Modern Family',
    "The Walking Dead",
    "The Flash",
    "Family Guy",
    "Ballers",
    "Mr. Robot",
    "Dark Matter",
    "Killjoys",
    "Baby Daddy",
    "Silicon Valley",
    "Game of Thrones",
    "Grimm"
]